version: '3.7'

services:
  fyber_messaging:
    build: .
    image: fyber_messaging
    container_name: fyber_messaging
    restart: on-failure
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:delegated
      - bundle_volume:/usr/local/bundle
    ports:
      - 3000:3000
    env_file:
      - .env

  postgres:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  apidocs:
    image: swaggerapi/swagger-ui
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data:
  bundle_volume:
